# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hway < Formula
  desc "Highway is a Decentralized Gateway which serves the Sonr Dynamic UI and a gateway to the blockchain API."
  homepage "https://sonr.io"
  version "0.14.3"
  license "OpenGLV3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sonrhq/sonr/releases/download/v0.14.3/hway-darwin-arm64.tar.gz"
      sha256 "228caab544e2210f023a024efac8d82bc0c9f897399dcb58707039e23d9bcee7"

      def install
        bin.install "hway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonrhq/sonr/releases/download/v0.14.3/hway-darwin-amd64.tar.gz"
      sha256 "b4fb5eb654895713660cb59964d091716f80fa422bd55f8caed3d7ccfa92d582"

      def install
        bin.install "hway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonrhq/sonr/releases/download/v0.14.3/hway-linux-arm64.tar.gz"
      sha256 "c0ee5f366823079bf6caf2ac6ee1e8207e0d8fa8956f6e9b8e9bc11ad4ddff48"

      def install
        bin.install "hway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonrhq/sonr/releases/download/v0.14.3/hway-linux-amd64.tar.gz"
      sha256 "42fa57328fde39b43c4392a962c5e70768ed6ee11e26fb42b84019cf1701d278"

      def install
        bin.install "hway"
      end
    end
  end

  def caveats
    <<~EOS
      Run the Sonr Highway with `hway`
    EOS
  end
end
