# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hway < Formula
  desc "Hway Binary Node"
  homepage "https://sonrhq.com"
  version "0.13.7"
  license "OpenGLV3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonrhq/sonr/releases/download/v0.13.7/hway-darwin-amd64.tar.gz"
      sha256 "781f074412b9f7e3c4eba9cb7b01c8007716f5b3bca369a6bc8f6c4cdebf5f11"

      def install
        bin.install "hway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonrhq/sonr/releases/download/v0.13.7/hway-darwin-arm64.tar.gz"
      sha256 "fe4d62e123a2f85855b534808c699cbe17d697cd79600663551efc58959c0bc2"

      def install
        bin.install "hway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonrhq/sonr/releases/download/v0.13.7/hway-linux-arm64.tar.gz"
      sha256 "0ed2d114741781487fef17a4029f395f1828bb4fc2e2965f93bb1dd590c2e121"

      def install
        bin.install "hway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonrhq/sonr/releases/download/v0.13.7/hway-linux-amd64.tar.gz"
      sha256 "063d186bed2cac372a0add01a3debbd8ea84a0d76e70f2da8c3f801e19caa441"

      def install
        bin.install "hway"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
