# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hway < Formula
  desc "Highway is a Decentralized Gateway which serves the Sonr Dynamic UI and a gateway to the blockchain API."
  homepage "https://sonr.io"
  version "0.14.3"
  license "OpenGLV3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sonrhq/sonr/releases/download/v0.14.3/hway-darwin-arm64.tar.gz"
      sha256 "cbdb6fa12ecdd33e9ba6605b2f423c05afdc51d552ad57d1a881ea4bd138dcc4"

      def install
        bin.install "hway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonrhq/sonr/releases/download/v0.14.3/hway-darwin-amd64.tar.gz"
      sha256 "e34c053757000802714d42a16839efba9c928fc6533e92e8ddf831f8fc69cd0e"

      def install
        bin.install "hway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonrhq/sonr/releases/download/v0.14.3/hway-linux-arm64.tar.gz"
      sha256 "91e924bcb8090bba2bae8d676a99c4d04d4bf4bdb01482c55a6df3a29e27838a"

      def install
        bin.install "hway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonrhq/sonr/releases/download/v0.14.3/hway-linux-amd64.tar.gz"
      sha256 "b92c3e525bd97988e0b4377cdf9c52be37b14df1f6b89dab1e3ac4c235696c1c"

      def install
        bin.install "hway"
      end
    end
  end

  def caveats
    <<~EOS
      Run the Sonr Highway with `hway`
    EOS
  end
end
