# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sonrd < Formula
  desc "Sonr Binary Node"
  homepage "https://sonrhq.com"
  version "0.13.11"
  license "OpenGLV3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sonrhq/sonr/releases/download/v0.13.11/sonrd-darwin-arm64.tar.gz"
      sha256 "2c379128ebd6d0a9c3220bddb6dbcb37b71e428c33c64c1674fe75bc6a5a5a07"

      def install
        bin.install "sonrd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonrhq/sonr/releases/download/v0.13.11/sonrd-darwin-amd64.tar.gz"
      sha256 "9f5c8218b633631d7db7839f748151710f2d28e52602c8e8984baa1e7ea5c61d"

      def install
        bin.install "sonrd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sonrhq/sonr/releases/download/v0.13.11/sonrd-linux-amd64.tar.gz"
      sha256 "a6f7c058b8d340ac2dd67ce7a80d6167cbe0001784678a74e1dbce53462ffea6"

      def install
        bin.install "sonrd"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
