# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sonrd < Formula
  desc "Sonr is an ibc-enabled blockchain for decentralized identity."
  homepage "https://sonr.io"
  version "0.1.1"
  license "OpenGLV3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sonrhq/sonr/releases/download/v0.1.1/sonrd-darwin-arm64.tar.gz"
      sha256 "61661481435813f8190dcb1aef50aa601436f87a0b3ac02d3c27541f748cea01"

      def install
        bin.install "sonrd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonrhq/sonr/releases/download/v0.1.1/sonrd-darwin-amd64.tar.gz"
      sha256 "67cc537abeaa6b222f4d2af733dae07a5841655c19b618c81304dcb5e2dcd4e7"

      def install
        bin.install "sonrd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonrhq/sonr/releases/download/v0.1.1/sonrd-linux-arm64.tar.gz"
      sha256 "06caaef5e7c8c0f1541beefa7288af3c195147590e3737c9e471f260a225e656"

      def install
        bin.install "sonrd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonrhq/sonr/releases/download/v0.1.1/sonrd-linux-amd64.tar.gz"
      sha256 "ac8bf148ee37cd6cb217a4c412d8c8b7e355a4ad2eedb9bc59f780e5e65e3672"

      def install
        bin.install "sonrd"
      end
    end
  end

  def caveats
    <<~EOS
      Run the Sonr Blockchain Node with `sonrd`
    EOS
  end
end
